# imports_granularity = "Crate"
# max_width = 120
# indent_style = "Block"
# format_strings = true
# group_imports = "One"
# format_code_in_doc_comments = true

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"