[package]
name = "kapta"
edition = "2021"
authors = ["LangPham"]
license = "MIT"
description = "Kapta ~ Map"
version.workspace = true
readme = "../README.md"

[dependencies]
geo = "0.26.0"
geo-types = {version="0.7.11", features = ["serde"]}
approx = "0.5"
